# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2eac8af074b2ed8402633158c9719a59"
name = "Syncup-for-clickup"
application_url = "https://syncup-for-clickup.vercel.app"
embedded = true

[access_scopes]
scopes = "read_orders"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/updated"
  topics = [ "orders/updated" ]

[auth]
redirect_urls = [ "https://syncup-for-clickup.vercel.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
