export const PLANS = {
  starter_monthly: {
    key: "starter_monthly",
    name: "Starter Monthly",
    price: 29.99,
    interval: "EVERY_30_DAYS",
    shopifyPlanName: "SyncUp Starter Monthly",
    annual: false,
    listLimit: 1,
    features: [
      "Unlimited orders synced",
      "1 ClickUp list connection",
      "Email support",
      "Full order to task sync",
      "Fulfillment to task completion sync",
    ],
  },
  starter_annual: {
    key: "starter_annual",
    name: "Starter Annual",
    price: 239,
    interval: "ANNUAL",
    shopifyPlanName: "SyncUp Starter Annual",
    annual: true,
    listLimit: 1,
    features: [
      "Unlimited orders synced",
      "1 ClickUp list connection",
      "Email support",
      "Full order to task sync",
      "Fulfillment to task completion sync",
    ],
  },
  growth_monthly: {
    key: "growth_monthly",
    name: "Growth Monthly",
    price: 49.99,
    interval: "EVERY_30_DAYS",
    shopifyPlanName: "SyncUp Growth Monthly",
    annual: false,
    listLimit: 5,
    features: [
      "Everything in Starter",
      "Up to 5 ClickUp list connections",
      "Priority support",
      "Sync analytics dashboard",
      "Auto-retry on failures (60s / 5m)",
    ],
  },
  growth_annual: {
    key: "growth_annual",
    name: "Growth Annual",
    price: 419,
    interval: "ANNUAL",
    shopifyPlanName: "SyncUp Growth Annual",
    annual: true,
    listLimit: 5,
    features: [
      "Everything in Starter",
      "Up to 5 ClickUp list connections",
      "Priority support",
      "Sync analytics dashboard",
      "Auto-retry on failures (60s / 5m)",
    ],
  },
};
