export const PLANS = {
  starter_monthly: {
    key: "starter_monthly",
    name: "Starter Monthly",
    price: 14.99,
    interval: "EVERY_30_DAYS",
    shopifyPlanName: "SyncUp Starter Monthly",
    annual: false,
    listLimit: 1,
    monthlyOrderLimit: 100,
    features: [
      "Up to 100 orders synced/month",
      "1 ClickUp list connection",
      "Email support",
      "Full order to task sync",
      "Fulfillment completion sync",
    ],
  },
  starter_annual: {
    key: "starter_annual",
    name: "Starter Annual",
    price: 99,
    interval: "ANNUAL",
    shopifyPlanName: "SyncUp Starter Annual",
    annual: true,
    listLimit: 1,
    monthlyOrderLimit: 100,
    features: [
      "Up to 100 orders synced/month",
      "1 ClickUp list connection",
      "Email support",
      "Full order to task sync",
      "Fulfillment completion sync",
    ],
  },
  growth_monthly: {
    key: "growth_monthly",
    name: "Growth Monthly",
    price: 29.99,
    interval: "EVERY_30_DAYS",
    shopifyPlanName: "SyncUp Growth Monthly",
    annual: false,
    listLimit: 5,
    monthlyOrderLimit: 500,
    features: [
      "Up to 500 orders synced/month",
      "Up to 5 ClickUp list connections",
      "Priority support",
      "Sync analytics dashboard",
      "Auto-retry on failures (60s / 5m)",
    ],
  },
  growth_annual: {
    key: "growth_annual",
    name: "Growth Annual",
    price: 199,
    interval: "ANNUAL",
    shopifyPlanName: "SyncUp Growth Annual",
    annual: true,
    listLimit: 5,
    monthlyOrderLimit: 500,
    features: [
      "Up to 500 orders synced/month",
      "Up to 5 ClickUp list connections",
      "Priority support",
      "Sync analytics dashboard",
      "Auto-retry on failures (60s / 5m)",
    ],
  },
  pro_monthly: {
    key: "pro_monthly",
    name: "Pro Monthly",
    price: 59.99,
    interval: "EVERY_30_DAYS",
    shopifyPlanName: "SyncUp Pro Monthly",
    annual: false,
    listLimit: 999, // Unlimited
    monthlyOrderLimit: null, // Unlimited
    features: [
      "Unlimited orders synced/month",
      "Unlimited ClickUp list connections",
      "Priority support",
      "Sync analytics dashboard",
      "Auto-retry on failures (60s / 5m)",
    ],
  },
  pro_annual: {
    key: "pro_annual",
    name: "Pro Annual",
    price: 399,
    interval: "ANNUAL",
    shopifyPlanName: "SyncUp Pro Annual",
    annual: true,
    listLimit: 999, // Unlimited
    monthlyOrderLimit: null, // Unlimited
    features: [
      "Unlimited orders synced/month",
      "Unlimited ClickUp list connections",
      "Priority support",
      "Sync analytics dashboard",
      "Auto-retry on failures (60s / 5m)",
    ],
  },
};
